version: "3.9"

services:
  java_app:
    container_name: java_app
    image: api-foro
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db-foro-alura:5432/db-foro-alura
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
    depends_on:
      - db-foro-alura

  db-foro-alura:
    container_name: db-foro-alura
    image: postgres:15.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db-foro-alura
    restart: always
    volumes:
      - data-db-foro-alura:/var/lib/postgresql/data


volumes:
  data-db-foro-alura: